# -*- coding: utf-8 -*-
"""Trabalho_Bigdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fuxjE1KIaZj-gx0uNJ3wQOKnWzhih0Of
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

from matplotlib import pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/bdbigdataeditado.csv", delimiter=';', encoding='utf-8')

print(df.head())

df['Erro Altura'] = ~df['Altura'].between(df['MinAut'], df['MaxAut'])

error_summary = df.groupby('Nome_Usuario').agg(
    Total_Medicoes=('Erro Altura', 'size'),
    Erros=('Erro Altura', 'sum')
)

error_summary['Porcentual Erro (%)'] = (error_summary['Erros'] / error_summary['Total_Medicoes']) * 100

error_summary.reset_index(inplace=True)
error_summary

df['Erro Peso'] = ~df['Peso_Embalagem'].between(df['MinPeso'], df['MaxPeso'])

error_summary = df.groupby('Nome_Usuario').agg(
    Total_Medicoes=('Erro Peso', 'size'),  # Use 'Erro Peso' here
    Erros=('Erro Peso', 'sum')  # Use 'Erro Peso' here
)

error_summary['Porcentual Erro (%)'] = (error_summary['Erros'] / error_summary['Total_Medicoes']) * 100
error_summary.reset_index(inplace=True)

error_summary

# @title Total_Medicoes vs Erros

from matplotlib import pyplot as plt
error_summary.plot(kind='scatter', x='Total_Medicoes', y='Erros', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title Total Measurements per User

import matplotlib.pyplot as plt

# Sample data (replace with your actual data)
users = ['airtontavares', 'manuelsousa', 'hebertsilva', 'user4', 'user5']
measurements = [159, 65, 16, 100, 80]  # Replace with actual Total_Medicoes data

plt.figure(figsize=(10, 6))
plt.bar(users, measurements, color='skyblue')
plt.xlabel('User')
plt.ylabel('Total Measurements')
plt.title('Total Measurements per User')
_ = plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels for better readability

print(error_summary)

error_summary['Porcentual Erro (%)'].plot(kind='hist', bins=20, title='Porcentual Erro (%) do Peso da Embalagem')
plt.gca().spines[['top', 'right']].set_visible(False)
plt.xlabel('Porcentagem de Erro')
plt.ylabel('Frequência')
plt.show()

# prompt: Use objpeso para fazer uma media de erro já que objpeso é o objetivo ele é uma coluna

# Calculate the mean error for 'Peso_Embalagem' relative to 'objpeso'
# Assuming 'objpeso' is a column in your dataframe

if 'ObjPeso' in df.columns:
    df['Erro Peso Relativo'] = abs(df['Peso_Embalagem'] - df['ObjPeso'])
    mean_error = df['Erro Peso Relativo'].mean()
    print(f"Mean Error (Peso_Embalagem relative to objpeso): {mean_error}")

    # You can also group by user and calculate the mean error per user
    error_by_user = df.groupby('Nome_Usuario')['Erro Peso Relativo'].mean()
    print("\nMean Error per User:")
    print(error_by_user)
else:
    print("'objpeso' column not found in the DataFrame.")

